class Fretboard:
    @abstractmethod
    def draw_borders(self):
        "this will create a polygon around the outside"
        pass

    @abstractmethod
    def draw_frets(self):
        "this will create frets as lines"
        pass

    @abstractmethod
    def draw_nut(self):
        "this will create a thicker fret at the point where strings enter headstock"
        pass

    @abstractmethod
    def draw_strings(self):
        "this will create horizontal lines where the strings are"
        pass

    @abstractmethod
    def draw_fretboard_markings(self):
        "this will draw those circles at certain frets to indicate 3,5,7,9,12"
        pass

    @abstractmethod
    def draw_external_markings(self):
        "these would be indicators for the notes generated by scale_mod"
        pass
